### ISSUE TITLE
Update input product validation for new static ancillary file

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pge#222]
The Beta release of the CSLC-S1 SAS now includes an additional "static" ancillary file defined within the RunConfig. The file path is defined within a new "static_ancillary_file_group" section of the SAS runconfig (see schema [here](https://github.com/opera-adt/COMPASS/blob/main/src/compass/schemas/s1_cslc_geo.yaml#L21)).

An example of how the new field looks within a SAS runconfig:

```
runconfig:
  name: cslc_s1_workflow_default

  groups:
      pge_name_group:
          pge_name: CSLC_S1_PGE

      ...
      static_ancillary_file_group:
          burst_database_file: input_data/opera_burst_database_deploy_2022_1212.sqlite3
      ...
```

The acceptance criteria for this ticket is to update the [validate_slc_s1_inputs](https://github.com/nasa/opera-sds-pge/blob/9aac542114419f7a52f2f2786cf1b41050c28590/src/opera/util/input_validation.py#L46) function to add validation of this new file. The "valid extensions" may be set to just ".sqlite3" for now.
