### ISSUE TITLE
DISP-S1 Stub Implemenatation and Initial Integration

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pge#268]
Ticket to create the stub implementation of the DISP-S1 PGE and integrate with the initial interface delivery of the corresponding SAS. Tasks include:

- [x] Creation of the `disp_s1` packages under both `src/opera/pge/` and `src/opera/test/pge/`
- [x] Creation of a stub `disp_s1_pge.py` module within `src/opera/pge` that contains the minimal implementations of the pre/post processor classes as well as the executor.
- [x] Creation of a stub `test_disp_s1_pge.py` module within `src/opera/test/pge/` with a single test case that performs a  instantiation of the stub PGE implementation.
- [x] Create Yamale schemas (baseline and algorithms) for the DISP-S1 SAS for inclusion within the `src/opera/pge/disp_s1/schema` directory. See below for more info on this.
- [x] Create the `Dockerfile_disp_s1` file within the `.ci/docker directory` that creates the combined PGE/SAS docker image
- [x] Create the `build_disp_s1.sh` and `test_disp_s1.sh` scripts under `.ci/scripts`. These can be based on the corresponding version for DSWx-HLS, but will need some tailoring to make them applicable to DISP-S1 (for example updating the artifactory path to the SAS docker base image)
- [x] Update the `build_all_images.sh` and `test_all_images.sh` scripts (also under `.ci/scripts`) to include the new scripts added in the previous task
- [x] Create an example runconfig for the DISP-S1 PGE named `disp_s1_sample_runconfig-v3.0.0-er.1.0.yaml` and populate it with both the PGE and SAS sections of the Runconfig. The sample SAS runconfig provided with the Interface delivery can be used as the example SAS portion.

Regarding the yamale schema files for DISP-S1: The SAS application ([dolphin](https://github.com/opera-adt/dolphin)) does not seem to maintain a static version of the schemas for the RunConfig files it can ingest. Rather, the application will only provide sample RunConfigs, from which we will need to reverse engineer the actual schema files so we can include them in our repo. 

What follows are the example RunConfigs for each of the schema types we will need to create.

**Main RunConfig**
```
input_file_group:
  # REQUIRED: List of paths to CSLC files.
  #   Type: array.
  cslc_file_list: []
  # REQUIRED: Frame ID of the bursts contained in `cslc_file_list`.
  #   Type: integer.
  frame_id:
dynamic_ancillary_file_group:
  # REQUIRED: Path to file containing SAS algorithm parameters.
  #   Type: string.
  algorithm_parameters_file:
  # Paths to existing Amplitude Dispersion file (1 per burst) for PS update calculation. If
  #   none provided, computed using the input SLC stack.
  #   Type: array.
  amplitude_dispersion_files: []
  # Paths to an existing Amplitude Mean files (1 per burst) for PS update calculation. If none
  #   provided, computed using the input SLC stack.
  #   Type: array.
  amplitude_mean_files: []
  # Paths to the incidence/azimuth-angle files (1 per burst). If none provided, corrections
  #   using incidence/azimuth-angle are skipped.
  #   Type: array.
  geometry_files: []
  # Optional Byte mask file used to ignore low correlation/bad data (e.g water mask).
  #   Convention is 0 for no data/invalid, and 1 for good data. Dtype must be uint8.
  #   Type: string.
  mask_file:
  # Path to the DEM file covering full frame. If none provided, corrections using DEM are
  #   skipped.
  #   Type: string.
  dem_file:
  # List of Paths to TEC files (1 per date) in IONEX format for ionosphere correction. If none
  #   provided, ionosphere corrections are skipped.
  #   Type: array.
  tec_files:
  # List of Paths to troposphere weather model files (1 per date). If none provided,
  #   troposphere corrections are skipped.
  #   Type: array.
  weather_model_files:
primary_executable:
  # Product type of the PGE.
  #   Type: string.
  product_type: DISP_S1_SINGLE
product_path_group:
  # REQUIRED: Directory where PGE will place results.
  #   Type: string.
  product_path:
  # Path to the scratch directory.
  #   Type: string.
  scratch_path: scratch
  # Path to the SAS output directory.
  #   Type: string.
  sas_output_path:
  # Version of the product.
  #   Type: string.
  product_version: '0.1'
  # Whether the SAS should output and save the Compressed SLCs in addition to the standard
  #   product output.
  #   Type: boolean.
  save_compressed_slc: false
  output_directory: output
worker_settings:
  # Whether to use GPU for processing (if available).
  #   Type: boolean.
  gpu_enabled: true
  # (For non-GPU) Number of cpu cores to use for Python multiprocessing. Uses
  #   `multiprocessing.cpu_count()` if not set.
  #   Type: integer.
  n_workers: 4
  # Number of threads to use per worker. This sets the OMP_NUM_THREADS environment variable in
  #   each python process.
  #   Type: integer.
  threads_per_worker: 1
  # Size (in GB) of blocks of data to load at a time.
  #   Type: number.
  block_size_gb: 1.0
# Path to the output log file in addition to logging to stderr.
#   Type: string.
log_file: output/disp_s1_workflow.log
```

**Algorithm Parameters Config**
```
ps_options:
  # Amplitude dispersion threshold to consider a pixel a PS.
  #   Type: number.
  amp_dispersion_threshold: 0.25
phase_linking:
  # Size of the ministack for sequential estimator.
  #   Type: integer.
  ministack_size: 15
  # Beta regularization parameter for correlation matrix inversion. 0 is no regularization.
  #   Type: number.
  beta: 0.01
  half_window:
    # Half window size (in pixels) for x direction.
    #   Type: integer.
    x: 11
    # Half window size (in pixels) for y direction.
    #   Type: integer.
    y: 5
interferogram_network:
  # For single-reference network: Index of the reference image in the network.
  #   Type: integer.
  reference_idx: 0
  # Max `n` to form the nearest-`n` interferograms by index.
  #   Type: integer.
  max_bandwidth:
  # Maximum temporal baseline of interferograms.
  #   Type: integer.
  max_temporal_baseline:
  # For manual-index network: List of (ref_idx, sec_idx) defining the interferograms to form.
  #   Type: array.
  indexes:
  # Type of interferogram network to create from phase-linking results.
  #   Type: string.
  #   Options: ['single-reference', 'manual-index', 'max-bandwidth', 'max-temporal-baseline'].
  network_type: single-reference
unwrap_options:
  # Whether to run the unwrapping step after wrapped phase estimation.
  #   Type: boolean.
  run_unwrap: true
  # Phase unwrapping method, passable to Tophu.
  #   Type: string.
  #   Options: ['snaphu', 'icu'].
  unwrap_method: snaphu
  # Number of tiles to split the unwrapping into (for Tophu).
  #   Type: array.
  tiles:
    - 1
    - 1
  # Initialization method for SNAPHU.
  #   Type: string.
  init_method: mcf
output_options:
  # Output (x, y) resolution (in units of input data).
  #   Type: object.
  output_resolution:
  # Alternative to specifying output resolution: Specify the (x, y) strides (decimation
  #   factor) to perform while processing input. For example, strides of [4, 2] would turn an
  #   input resolution of [5, 10] into an output resolution of [20, 20].
  #   Type: object.
  strides:
    x: 1
    y: 1
  # Options for `create_dataset` with h5py.
  #   Type: object.
  hdf5_creation_options:
    chunks:
      - 128
      - 128
    compression: gzip
    compression_opts: 4
    shuffle: true
  # GDAL creation options for GeoTIFF files.
  #   Type: array.
  gtiff_creation_options:
    - COMPRESS=DEFLATE
    - ZLEVEL=4
    - TILED=YES
    - BLOCKXSIZE=128
    - BLOCKYSIZE=128
# Name of the subdataset to use in the input NetCDF files.
#   Type: string.
subdataset: science/SENTINEL1/CSLC/grids/VV
```

Using the documentation for these sample configs, it should be possible to write the corresponding Yamale schema.
